name: Build and Deploy to AKS

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: fastapiacr1052.azurecr.io
  IMAGE_NAME: fastapi-utm

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # create unique tag
    - name: Set tag
      id: vars
      run: echo "TAG=$(date +%s)" >> $GITHUB_OUTPUT

    # login ACR
    - name: Login ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # multi arch build
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Build & Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
        platforms: linux/amd64,linux/arm64

    # setup kubeconfig
    - name: Set kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    # inject image into manifest
    - name: Replace image in manifest
      run: |
        sed -i "s|IMAGE_PLACEHOLDER|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}|g" k8s/deployment.yaml

    # deploy
    - name: Apply manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
